
export const LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: '한국어', flag: '🇰🇷' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
];

export const TRANSLATIONS: Record<string, any> = {
  en: {
    heroTitle: "Optimise your CV/Resume",
    heroTitleHighlight: "in seconds",
    heroSubtitle: "Paste your target job description and let our AI tailour your CV/Resume to pass ATS filters and stand out to recruiters.",
    step1: "Requirements",
    step2: "Upload",
    step3: "Optimise",
    jdLabel: "Job Description",
    jdSubLabel: "PASTE YOUR TARGET ROLE REQUIREMENTS",
    jdPlaceholder: "Paste the target Job Description here...",
    clear: "CLEAR",
    yourResume: "Your CV/Resume",
    resumeSubLabel: "SOURCE FILE / TEXT",
    uploadResume: "Upload CV/Resume",
    uploadResumeSub: "DRAG FILE OR CLICK TO UPLOAD (.DOCX, .PDF)",
    pasteResume: "Paste CV/Resume",
    pasteResumeSub: "DIRECTLY PASTE PLAIN TEXT",
    uploadProject: "Upload Portfolio",
    uploadProjectSub: "DRAG FILES OR CLICK TO UPLOAD (ANY MEDIA)",
    optimizeResume: "Optimise CV/Resume",
    analyzeProject: "Analyse Project",
    analyzing: "Analysing...",
    timeEstimate: "Estimated time: ~15-20 seconds",
    matchScore: "Core Skills",
    basedOn: "Based on keyword matching & requirements",
    backToUpload: "← Back to Upload mode",
    pastePlaceholder: "Paste your existing CV/resume text here...",
    modeAI: "AI Optimisation",
    modeManual: "Manual Builder",
    manualTitle: "Build from Scratch",
    manualSubtitle: "Start with a professional template and fill in your details manually.",
    startManual: "Create New CV/Resume",
    resSummary: "PROFESSIONAL SUMMARY",
    resEducation: "EDUCATION",
    resExperience: "PROFESSIONAL EXPERIENCE",
    resProjects: "PROJECTS",
    resAwards: "HONOURS & AWARDS",
    resReferences: "REFERENCES",
    resVolunteering: "VOLUNTEERING",
    resSkills: "SKILLS",
    resProfile: "PROFILE",
    tmplMinimalist: "Minimalist",
    tmplMinimalistDesc: "Clean & modern (Sans-serif)",
    tmplProfessional: "Professional",
    tmplProfessionalDesc: "Classic & structured (Serif)",
    tmplCreative: "Creative",
    tmplCreativeDesc: "Two-column, visually engaging",
    tmplAcademic: "Academic",
    tmplAcademicDesc: "Education-first, detail-focused",
    tmplGrid: "Grid",
    tmplGridDesc: "Modern sidebar layout",
    designSystem: "Design System",
    publish: "PUBLISH",
    themeAccent: "Theme Colour",
    inventory: "Inventory",
    editContent: "Edit Content",
    createNewDesign: "Create New Design",
    saveChanges: "Save Changes",
    publishOnline: "PUBLISH ONLINE",
    addProjects: "Add Projects",
    importWebsite: "Import Website",
    enterWebsiteUrl: "Enter your website URL (e.g., https://myportfolio.com):",
    clearAll: "Clear All Data",
    resumeBuilder: "CV/Resume Builder",
    portfolioAi: "Portfolio AI",
    interview: "Interview",
    careerPath: "Career Path",
    interviewLab: "Interview Lab",
    practiceContext: "Practice Context",
    recruiter: "Recruiter",
    duration: "Duration",
    mode: "Mode",
    startSession: "START SESSION",
    liveInfo: "Live Info",
    muteMic: "MUTE MIC",
    unmuteMic: "UNMUTE MIC",
    expertFeedback: "Expert Feedback",
    history: "History",
    intResumeJd: "CV/RESUME JD",
    intCustom: "CUSTOM",
    intCustomPlaceholder: "Paste specific requirements...",
    intOlivia: "Olivia",
    intJames: "James",
    intModeText: "Text",
    intModeVoice: "Voice",
    intModeFace: "Face",
    intEnd: "END",
    intLiveVision: "Live Vision Analysis",
    intExpression: "Expression",
    intEyeContact: "Eye Contact",
    intGeneratingReport: "Generating Performance Report...",
    intReportSubtitle: "Analysing speech patterns, content, and sentiment.",
    intStudioTitle: "AI Recruiter Studio",
    intStudioReady: "Ready for your high-stakes simulation.",
    intStudioWarmup: "Warming up the studio...",
    intHistoryTitle: "History",
    intHistorySubtitle: "Previous Logs",
    intHistoryReset: "Reset",
    intNoSessions: "No Sessions Found",
    intEvaluationTitle: "Interview Evaluation",
    intEvaluationSubtitle: "CONFIDENTIAL CANDIDATE REPORT",
    intTotalScore: "Total Score",
    intExecSummary: "Executive Summary",
    intStrengths: "Peak Strengths",
    intGrowth: "Growth Areas",
    intMisses: "Critical Misses",
    intTranscript: "Transcript Analysis",
    intDownloadPdf: "Download PDF Report",
    intClose: "Close",
    intTime: "Time",
    intBy: "By",
    intLen: "Len",
    intListening: "Listening",
    intStandby: "Standby",
    intProcessing: "Processing...",
    intTypeResponse: "Type response...",
    intSpeakNow: "I'm listening, please speak...",
    cpAiTitle: "Career Strategy AI",
    cpMapFuture: "Map Your Future.",
    cpSubtitle: "Starting from your current status in 2026, our AI evaluates every project to build your unique professional trajectory.",
    cpAutoTrajectory: "Auto Trajectory",
    cpBasedOnResume: "Based on Current CV/Resume",
    cpTargetedPivot: "Targeted Pivot",
    cpAimSpecific: "Aim for a Specific Role",
    cpRecentStrategies: "Recent Strategies",
    cpStartOver: "Start Over",
    cpTimeline: "Timeline (Start: 2026)",
    cpTargetGoal: "TARGET GOAL",
    cpAnalyzing: "Analysing Career Data",
    cpBestFit: "Best Fit",
    cpMatch: "Match",
    cpViewStrategy: "View Strategy",
    cpGenerating: "Generating...",
    cpConfidential: "Confidential Report",
    cpDownloadPdf: "Download PDF",
    cpSkillGap: "Skill Gap Analysis",
    cpInterviewPrep: "Interview Prep",
    cpPortfolioProjects: "Portfolio Projects",
    cpSavedPlans: "Saved Plans",
    cpCareerRoadmaps: "Career Roadmaps",
    cpClear: "Clear",
    cpNoSaved: "No Saved Strategies",
    cpTargetPlaceholder: "Target Role (e.g. APAC Digital Marketing Manager)",
    cpPredict: "Predict",
    cpCurrentResume: "Current CV/Resume",
    cpUploadNew: "Upload New PDF",
    cpCancel: "Cancel",
    coachTriggerMessage: "{name}, I see you've downloaded the deployment strategy for {role}. Would you like me to help you brainstorm some specific project ideas to fill the Budget Management gap we identified earlier?",
    disclaimer: "AI Fast Resume is an AI-powered assistant; please review all generated content for accuracy.",
    authLoginRegister: "Login / Register",
    authGoogleOneTap: "Google One-Tap",
    authOr: "OR",
    authEmailAddress: "Email Address",
    authPassword: "Password",
    authEmailButton: "Email Login / Register",
    authLoggedIn: "Logged In",
    authProcessing: "Processing...",
    authVerifyEmail: "Verification email sent! Please check your inbox.",
    finalizing: "Finalising...",
    optimizingAts: "OPTIMISING FOR ATS COMPATIBILITY",
    overallScore: "Overall Score",
    basedOnMatch: "BASED ON JOB MATCH & QUALITY",
    atsBreakdown: "ATS Analysis Breakdown",
    coreSkillsMatch: "CORE SKILLS MATCH",
    quantifiedStar: "QUANTIFIED ACHIEVEMENTS (STAR)",
    industryRelevance: "INDUSTRY RELEVANCE",
    formattingHealth: "FORMATTING & HEALTH",
    hardSkillsFound: "HARD SKILLS FOUND",
    missingKeywords: "MISSING KEYWORDS",
    atsMatch: "ATS MATCH",
    showBullets: "SHOW BULLETS",
    hideBullets: "HIDE BULLETS",
    generateTailored: "Generate Tailored CV/Resume",
    step3Finalizing: "Step 3 of 3: Finalising your custom document",
    resume: "CV/RESUME",
    coverLetter: "COVER LETTER",
    resumeLayouts: "CV/RESUME LAYOUTS",
    fontSelection: "FONT SELECTION",
    coachGreeting: "Hello! I'm your AI Career Coach. I've analyzed your resume and portfolio. Your current Health Score is: {score}/100. How can I help you improve your application today?",
  },
  zh: {
    heroTitle: "几秒钟内",
    heroTitleHighlight: "优化您的简历",
    heroSubtitle: "粘贴您的目标职位描述，让 AI 为您量身定制简历，轻松通过 ATS 筛选并脱颖而出。",
    step1: "职位要求",
    step2: "上传",
    step3: "智能优化",
    jdLabel: "职位描述",
    jdSubLabel: "粘贴目标职位要求",
    jdPlaceholder: "在此处粘贴目标职位描述...",
    clear: "清空",
    yourResume: "您的简历",
    resumeSubLabel: "源文件 / 文本",
    uploadResume: "上传简历",
    uploadResumeSub: "拖拽文件或点击上传 (.DOCX, .PDF)",
    pasteResume: "粘贴简历",
    pasteResumeSub: "直接粘贴纯文本",
    uploadProject: "上传作品集",
    uploadProjectSub: "拖拽文件或点击上传 (任何媒体)",
    optimizeResume: "优化简历",
    analyzeProject: "分析项目",
    analyzing: "分析中...",
    timeEstimate: "预计耗时：约 15-20 秒",
    matchScore: "核心技能",
    basedOn: "基于关键词匹配和职位要求",
    backToUpload: "← 返回上传模式",
    pastePlaceholder: "在此粘贴您现有的简历文本...",
    modeAI: "AI 智能优化",
    modeManual: "手动创建",
    manualTitle: "从零开始构建",
    manualSubtitle: "选择我们的专业模板并手动填写您的详细信息。",
    startManual: "创建新简历",
    resSummary: "个人简介",
    resEducation: "教育背景",
    resExperience: "工作经历",
    resProjects: "项目经验",
    resAwards: "荣誉奖项",
    resReferences: "推荐人",
    resVolunteering: "志愿服务",
    resSkills: "技能特长",
    resProfile: "个人资料",
    tmplMinimalist: "极简风格",
    tmplMinimalistDesc: "干净现代 (无衬线)",
    tmplProfessional: "专业风格",
    tmplProfessionalDesc: "经典结构 (衬线体)",
    tmplCreative: "创意风格",
    tmplCreativeDesc: "双栏布局，视觉吸引",
    tmplAcademic: "学术风格",
    tmplAcademicDesc: "教育优先，注重细节",
    tmplGrid: "网格风格",
    tmplGridDesc: "现代侧边栏布局",
    designSystem: "设计系统",
    publish: "发布",
    themeAccent: "主题色",
    inventory: "项目清单",
    editContent: "编辑内容",
    createNewDesign: "创建新设计",
    saveChanges: "保存更改",
    publishOnline: "在线发布",
    addProjects: "添加项目",
    importWebsite: "导入网站",
    enterWebsiteUrl: "输入您的网站 URL (例如 https://myportfolio.com):",
    clearAll: "清空所有数据",
    resumeBuilder: "简历生成器",
    portfolioAi: "作品集 AI",
    interview: "面试训练",
    careerPath: "职业路径",
    interviewLab: "面试实验室",
    practiceContext: "练习背景",
    recruiter: "面试官",
    duration: "时长",
    mode: "模式",
    startSession: "开始面试",
    liveInfo: "实时信息",
    muteMic: "静音",
    unmuteMic: "取消静音",
    expertFeedback: "专家反馈",
    history: "历史记录",
    intResumeJd: "使用简历JD",
    intCustom: "自定义",
    intCustomPlaceholder: "粘贴具体要求...",
    intOlivia: "Olivia",
    intJames: "James",
    intModeText: "文本",
    intModeVoice: "语音",
    intModeFace: "视频",
    intEnd: "结束",
    intLiveVision: "实时视觉分析",
    intExpression: "表情",
    intEyeContact: "眼神接触",
    intGeneratingReport: "正在生成表现报告...",
    intReportSubtitle: "分析语音模式、内容和情绪。",
    intStudioTitle: "AI 招聘演播室",
    intStudioReady: "准备好进行高风险模拟。",
    intStudioWarmup: "演播室预热中...",
    intHistoryTitle: "历史记录",
    intHistorySubtitle: "以前的日志",
    intHistoryReset: "重置",
    intNoSessions: "未找到会话",
    intEvaluationTitle: "面试评估",
    intEvaluationSubtitle: "机密候选人报告",
    intTotalScore: "总分",
    intExecSummary: "执行摘要",
    intStrengths: "核心优势",
    intGrowth: "提升空间",
    intMisses: "关键失误",
    intTranscript: "逐字稿分析",
    intDownloadPdf: "下载 PDF 报告",
    intClose: "关闭",
    intTime: "时间",
    intBy: "面试官",
    intLen: "时长",
    intListening: "倾听中",
    intStandby: "待机",
    intProcessing: "处理中...",
    intTypeResponse: "输入回答...",
    intSpeakNow: "我在听，请说话...",
    cpAiTitle: "职业策略 AI",
    cpMapFuture: "规划你的未来。",
    cpSubtitle: "从 2026 年的现状开始，AI 将评估每个项目，构建你独特的职业轨迹。",
    cpAutoTrajectory: "自动轨迹",
    cpBasedOnResume: "基于当前简历",
    cpTargetedPivot: "目标转型",
    cpAimSpecific: "针对特定职位",
    cpRecentStrategies: "最近的策略",
    cpStartOver: "重新开始",
    cpTimeline: "时间轴 (开始: 2026)",
    cpTargetGoal: "目标",
    cpAnalyzing: "正在分析职业数据",
    cpBestFit: "最匹配",
    cpMatch: "匹配度",
    cpViewStrategy: "查看策略",
    cpGenerating: "生成中...",
    cpConfidential: "机密报告",
    cpDownloadPdf: "下载 PDF",
    cpSkillGap: "技能差距分析",
    cpInterviewPrep: "面试准备",
    cpPortfolioProjects: "作品集项目",
    cpSavedPlans: "已保存计划",
    cpCareerRoadmaps: "职业路线图",
    cpClear: "清除",
    cpNoSaved: "无已保存策略",
    cpTargetPlaceholder: "目标职位 (例如: 亚太区数字营销经理)",
    cpPredict: "预测",
    cpCurrentResume: "当前简历",
    cpUploadNew: "上传新 PDF",
    cpCancel: "取消",
    coachTriggerMessage: "{name}，我看到你下载了 {role} 的部署策略。需要我帮你构思一些具体项目创意，来填补我们之前发现的预算管理技能空白吗？",
    disclaimer: "AI Fast Resume 是一款 AI 辅助工具；请务必核对所有生成内容的准确性。",
    authLoginRegister: "登录 / 注册",
    authGoogleOneTap: "Google 一键登录",
    authOr: "或",
    authEmailAddress: "邮箱地址",
    authPassword: "密码",
    authEmailButton: "邮箱 登录 / 注册",
    authLoggedIn: "已登录",
    authProcessing: "正在处理...",
    authVerifyEmail: "验证邮件已发送！请检查您的收件箱。",
    finalizing: "正在完成...",
    optimizingAts: "正在优化 ATS 兼容性",
    overallScore: "总分",
    basedOnMatch: "基于职位匹配度与质量",
    atsBreakdown: "ATS 分析详情",
    coreSkillsMatch: "核心技能匹配",
    quantifiedStar: "量化成就 (STAR)",
    industryRelevance: "行业相关性",
    formattingHealth: "格式与健康度",
    hardSkillsFound: "已发现的硬技能",
    missingKeywords: "缺失关键词",
    atsMatch: "ATS 匹配",
    showBullets: "显示要点",
    hideBullets: "隐藏要点",
    generateTailored: "生成定制简历",
    step3Finalizing: "第 3 步（共 3 步）：正在完成您的定制文档",
    resume: "简历",
    coverLetter: "求职信",
    resumeLayouts: "简历布局",
    fontSelection: "字体选择",
    coachGreeting: "你好！我是你的 AI 职业教练。我已经分析了你的简历和作品集。目前的健康得分为：{score}/100。今天我能帮你做些什么来提升你的申请竞争力？",
  },
  ja: {
    heroTitle: "履歴書を最適化",
    heroTitleHighlight: "数秒で完了",
    heroSubtitle: "ターゲットとなる職務内容を貼り付けるだけで、AIがATSフィルターを通過し、採用担当者の目に留まるように履歴書を調整します。",
    step1: "要件",
    step2: "アップロード",
    step3: "最適化",
    jdLabel: "職務内容",
    jdSubLabel: "ターゲットの職務要件を貼り付け",
    jdPlaceholder: "ここに職務内容を貼り付けてください...",
    clear: "クリア",
    yourResume: "あなたの履歴書",
    resumeSubLabel: "ソースファイル / テキスト",
    uploadResume: "履歴書をアップロード",
    uploadResumeSub: "ファイルをドラッグまたはクリックしてアップロード (.DOCX, .PDF)",
    pasteResume: "履歴書を貼り付け",
    pasteResumeSub: "プレーンテキストを直接貼り付け",
    uploadProject: "ポートフォリオをアップロード",
    uploadProjectSub: "ファイルをドラッグまたはクリックしてアップロード",
    optimizeResume: "履歴書を最適化",
    analyzeProject: "プロジェクトを分析",
    analyzing: "分析中...",
    timeEstimate: "推定時間：約15〜20秒",
    matchScore: "コアスキル",
    basedOn: "キーワードの一致と要件に基づく",
    backToUpload: "← アップロードモードに戻る",
    pastePlaceholder: "既存の履歴書テキストをここに貼り付けてください...",
    modeAI: "AI最適化",
    modeManual: "手動作成",
    manualTitle: "ゼロから作成",
    manualSubtitle: "プロフェッショナルなテンプレートを選択し、詳細を手動で入力します。",
    startManual: "新しい履歴書を作成",
    resSummary: "プロフェッショナルサマリー",
    resEducation: "学歴",
    resExperience: "職歴",
    resProjects: "プロジェクト",
    resAwards: "受賞歴・表彰",
    resReferences: "推薦人",
    resVolunteering: "ボランティア",
    resSkills: "スキル",
    resProfile: "プロフィール",
    tmplMinimalist: "ミニマリスト",
    tmplMinimalistDesc: "クリーン＆モダン (サンセリフ)",
    tmplProfessional: "プロフェッショナル",
    tmplProfessionalDesc: "クラシック＆構造的 (セリフ)",
    tmplCreative: "クリエイティブ",
    tmplCreativeDesc: "2カラム、視覚的に魅力的",
    tmplAcademic: "アカデミック",
    tmplAcademicDesc: "学歴重視、詳細重視",
    tmplGrid: "グリッド",
    tmplGridDesc: "モダンなサイドバーレイアウト",
    designSystem: "デザインシステム",
    publish: "公開",
    themeAccent: "アクセントカラー",
    inventory: "インベントリ",
    editContent: "内容を編集",
    createNewDesign: "新しいデザインを作成",
    saveChanges: "変更を保存",
    publishOnline: "オンラインで公開",
    addProjects: "プロジェクトを追加",
    importWebsite: "ウェブサイトをインポート",
    enterWebsiteUrl: "ウェブサイトのURLを入力してください (例: https://myportfolio.com):",
    clearAll: "全データを消去",
    resumeBuilder: "履歴書作成",
    portfolioAi: "ポートフォリオAI",
    interview: "面接練習",
    careerPath: "キャリアパス",
    interviewLab: "面接ラボ",
    practiceContext: "練習コンテキスト",
    recruiter: "面接官",
    duration: "時間",
    mode: "モード",
    startSession: "セッション開始",
    liveInfo: "ライブ情報",
    muteMic: "マイクミュート",
    unmuteMic: "mute解除",
    expertFeedback: "エキスパートフィードバック",
    history: "履歴",
    intResumeJd: "履歴書JDを使用",
    intCustom: "カスタム",
    intCustomPlaceholder: "特定の要件を貼り付け...",
    intOlivia: "オリビア",
    intJames: "ジェームズ",
    intModeText: "テキスト",
    intModeVoice: "音声",
    intModeFace: "ビデオ",
    intEnd: "終了",
    intLiveVision: "ライブビジョン分析",
    intExpression: "表情",
    intEyeContact: "アイコンタクト",
    intGeneratingReport: "パフォーマンスレポートを作成中...",
    intReportSubtitle: "発話パターン、内容、感情を分析しています。",
    intStudioTitle: "AIリクルータースタジオ",
    intStudioReady: "ハイステークスシミュレーションの準備完了。",
    intStudioWarmup: "スタジオを準備中...",
    intHistoryTitle: "履歴",
    intHistorySubtitle: "過去のログ",
    intHistoryReset: "リセット",
    intNoSessions: "セッションが見つかりません",
    intEvaluationTitle: "面接評価",
    intEvaluationSubtitle: "機密候補者レポート",
    intTotalScore: "総合スコア",
    intExecSummary: "エグゼクティブサマリー",
    intStrengths: "主な強み",
    intGrowth: "成長分野",
    intMisses: "重大なミス",
    intTranscript: "トランスクリプト分析",
    intDownloadPdf: "PDFレポートをダウンロード",
    intClose: "閉じる",
    intTime: "時間",
    intBy: "担当",
    intLen: "長さ",
    intListening: "聞いています",
    intStandby: "スタンバイ",
    intProcessing: "処理中...",
    intTypeResponse: "回答を入力...",
    intSpeakNow: "聞いています、お話しください...",
    cpAiTitle: "キャリア戦略AI",
    cpMapFuture: "未来を描く。",
    cpSubtitle: "2026年の現状から、AIがプロジェクトを評価し、独自のキャリア軌道を構築します。",
    cpAutoTrajectory: "自動軌道予測",
    cpBasedOnResume: "現在の履歴書に基づく",
    cpTargetedPivot: "ターゲット転換",
    cpAimSpecific: "特定の役割を目指す",
    cpRecentStrategies: "最近の戦略",
    cpStartOver: "やり直す",
    cpTimeline: "タイムライン (開始: 2026)",
    cpTargetGoal: "目標",
    cpAnalyzing: "キャリアデータを分析中",
    cpBestFit: "最適",
    cpMatch: "一致率",
    cpViewStrategy: "戦略を見る",
    cpGenerating: "生成中...",
    cpConfidential: "機密レポート",
    cpDownloadPdf: "PDFをダウンロード",
    cpSkillGap: "スキルギャップ分析",
    cpInterviewPrep: "面接準備",
    cpPortfolioProjects: "ポートフォリオプロジェクト",
    cpSavedPlans: "保存されたプラン",
    cpCareerRoadmaps: "キャリアロードマップ",
    cpClear: "クリア",
    cpNoSaved: "保存された戦略はありません",
    cpTargetPlaceholder: "目標の役割 (例: APACデジタルマーケティングマネージャー)",
    cpPredict: "予測",
    cpCurrentResume: "現在の履歴書",
    cpUploadNew: "新しいPDFをアップロード",
    cpCancel: "キャンセル",
    coachTriggerMessage: "{name}さん、{role} の展開戦略をダウンロードされたようですね。以前特定した予算管理のギャップを埋めるための具体的なプロジェクトのアイデア出しをお手伝いしましょうか？",
    disclaimer: "AI Fast Resume は AI 搭載のアシスタントです。生成されたすべての内容の正確性を確認してください。",
    authLoginRegister: "ログイン / 登録",
    authGoogleOneTap: "Google ワンタップ",
    authOr: "または",
    authEmailAddress: "メールアドレス",
    authPassword: "パスワード",
    authEmailButton: "メールでログイン / 登録",
    authLoggedIn: "ログイン済み",
    authProcessing: "処理中...",
    authVerifyEmail: "確認メールを送信しました。受信トレイを確認してください。",
    coachGreeting: "こんにちは！AIキャリアコーチです。履歴書とポートフォリオを分析しました。現在のヘルススコアは {score}/100 です。本日はどのようにアプリケーションの改善をお手伝いしましょうか？",
  },
  ko: {
    heroTitle: "이력서 최적화",
    heroTitleHighlight: "몇 초 만에",
    heroSubtitle: "목표 채용 공고를 붙여넣으면 AI가 ATS 필터를 통과하고 채용 담당자의 눈에 띄도록 이력서를 맞춤 조정해 드립니다.",
    step1: "요구사항",
    step2: "업로드",
    step3: "최적화",
    jdLabel: "직무 설명",
    jdSubLabel: "목표 역할 요구사항 붙여넣기",
    jdPlaceholder: "여기에 직무 설명을 붙여넣으세요...",
    clear: "지우기",
    yourResume: "내 이력서",
    resumeSubLabel: "소스 파일 / 텍스트",
    uploadResume: "이력서 업로드",
    uploadResumeSub: "파일을 끌어오거나 클릭하여 업로드 (.DOCX, .PDF)",
    pasteResume: "이력서 붙여넣기",
    pasteResumeSub: "일반 텍스트를 직접 붙여넣기",
    uploadProject: "포트폴리오 업로드",
    uploadProjectSub: "파일을 끌어오거나 클릭하여 업로드",
    optimizeResume: "이력서 최적화",
    analyzeProject: "프로젝트 분석",
    analyzing: "분석 중...",
    timeEstimate: "예상 소요 시간: 약 15-20초",
    matchScore: "핵심 기술",
    basedOn: "키워드 매칭 및 요구사항 기준",
    backToUpload: "← 업로드 모드로 돌아가기",
    pastePlaceholder: "여기에 기존 이력서 텍스트를 붙여넣으세요...",
    modeAI: "AI 최적화",
    modeManual: "수동 작성",
    manualTitle: "처음부터 작성하기",
    manualSubtitle: "전문 템플릿을 선택하고 세부 정보를 직접 입력하세요.",
    startManual: "새 이력서 만들기",
    resSummary: "전문 요약",
    resEducation: "학력",
    resExperience: "경력",
    resProjects: "프로젝트",
    resAwards: "수상 및 명예",
    resReferences: "참고인",
    resVolunteering: "봉사 활동",
    resSkills: "보유 기술",
    resProfile: "프로필",
    tmplMinimalist: "미니멀리스트",
    tmplMinimalistDesc: "깔끔하고 현대적 (산세리프)",
    tmplProfessional: "전문가",
    tmplProfessionalDesc: "클래식하고 구조적 (세리프)",
    tmplCreative: "크리에이티브",
    tmplCreativeDesc: "2단 컬럼, 시각적 매력",
    tmplAcademic: "아카데믹",
    tmplAcademicDesc: "교육 중심, 세부 사항 중시",
    tmplGrid: "그리드",
    tmplGridDesc: "현대적인 사이드바 레이아웃",
    designSystem: "디자인 시스템",
    publish: "게시",
    themeAccent: "테마 색상",
    inventory: "인벤토리",
    editContent: "컨텐츠 편집",
    createNewDesign: "새 디자인 만들기",
    saveChanges: "변경사항 저장",
    publishOnline: "온라인 게시",
    addProjects: "프로젝트 추가",
    importWebsite: "웹사이트 가져오기",
    enterWebsiteUrl: "웹사이트 URL을 입력하세요 (예: https://myportfolio.com):",
    clearAll: "모든 데이터 삭제",
    resumeBuilder: "이력서 빌더",
    portfolioAi: "포트폴리오 AI",
    interview: "면접 연습",
    careerPath: "커리어 경로",
    interviewLab: "인터뷰 랩",
    practiceContext: "연습 문맥",
    recruiter: "면접관",
    duration: "기간",
    mode: "모드",
    startSession: "세션 시작",
    liveInfo: "라이브 정보",
    muteMic: "마이크 음소거",
    unmuteMic: "음소거 해제",
    expertFeedback: "전문가 피드백",
    history: "히스토리",
    intResumeJd: "이력서 JD",
    intCustom: "사용자 정의",
    intCustomPlaceholder: "구체적인 요구사항 붙여넣기...",
    intOlivia: "올리비아",
    intJames: "제임스",
    intModeText: "텍스트",
    intModeVoice: "음성",
    intModeFace: "영상",
    intEnd: "종료",
    intLiveVision: "라이브 비전 분석",
    intExpression: "표정",
    intEyeContact: "시선 맞춤",
    intGeneratingReport: "성과 보고서 생성 중...",
    intReportSubtitle: "음성 패턴, 콘텐츠 및 감정을 분석합니다.",
    intStudioTitle: "AI 채용 스튜디오",
    intStudioReady: "고위험 시뮬레이션 준비 완료.",
    intStudioWarmup: "스튜디오 예열 중...",
    intHistoryTitle: "히스토리",
    intHistorySubtitle: "이전 로그",
    intHistoryReset: "초기화",
    intNoSessions: "세션 없음",
    intEvaluationTitle: "면접 평가",
    intEvaluationSubtitle: "기밀 후보자 보고서",
    intTotalScore: "총점",
    intExecSummary: "요약",
    intStrengths: "강점",
    intGrowth: "성장 분야",
    intMisses: "주요 실수",
    intTranscript: "대본 분석",
    intDownloadPdf: "PDF 보고서 다운로드",
    intClose: "닫기",
    intTime: "시간",
    intBy: "면접관",
    intLen: "길이",
    intListening: "듣는 중",
    intStandby: "대기",
    intProcessing: "처리 중...",
    intTypeResponse: "답변 입력...",
    intSpeakNow: "듣고 있습니다, 말씀해 주세요...",
    cpAiTitle: "커리어 전략 AI",
    cpMapFuture: "미래를 설계하세요.",
    cpSubtitle: "2026년 현재 상태에서 시작하여, AI가 모든 프로젝트를 평가하고 고유한 커리어 경로를 구축합니다.",
    cpAutoTrajectory: "자동 경로 예측",
    cpBasedOnResume: "현재 이력서 기반",
    cpTargetedPivot: "목표 전환",
    cpAimSpecific: "특정 역할 목표",
    cpRecentStrategies: "최근 전략",
    cpStartOver: "다시 시작",
    cpTimeline: "타임라인 (시작: 2026)",
    cpTargetGoal: "목표",
    cpAnalyzing: "커리어 데이터 분석 중",
    cpBestFit: "최적합",
    cpMatch: "일치율",
    cpViewStrategy: "전략 보기",
    cpGenerating: "생성 중...",
    cpConfidential: "기밀 보고서",
    cpDownloadPdf: "PDF 다운로드",
    cpSkillGap: "기술 격차 분석",
    cpInterviewPrep: "면접 준비",
    cpPortfolioProjects: "포트폴리오 프로젝트",
    cpSavedPlans: "저장된 계획",
    cpCareerRoadmaps: "커리어 로드맵",
    cpClear: "지우기",
    cpNoSaved: "저장된 전략 없음",
    cpTargetPlaceholder: "목표 역할 (예: APAC 디지털 마케팅 매니저)",
    cpPredict: "예측",
    cpCurrentResume: "현재 이력서",
    cpUploadNew: "새 PDF 업로드",
    cpCancel: "취소",
    coachTriggerMessage: "{name}님, {role}에 대한 배포 전략을 다운로드하셨군요. 이전에 확인된 예산 관리 격차를 메우기 위한 구체적인 프로젝트 아이디어를 브레인스토밍하도록 도와드릴까요?",
    disclaimer: "AI Fast Resume는 AI 기반 어시스턴트입니다. 생성된 모든 내용의 정확성을 검토해 주세요.",
    authLoginRegister: "로그인 / 회원가입",
    authGoogleOneTap: "Google 원탭",
    authOr: "또는",
    authEmailAddress: "이메일 주소",
    authPassword: "비밀번호",
    authEmailButton: "이메일 로그인 / 회원가입",
    authLoggedIn: "로그인됨",
    authProcessing: "처리 중...",
    authVerifyEmail: "인증 이메일이 전송되었습니다! 받은 편지함을 확인하세요.",
    coachGreeting: "안녕하세요! AI 커리어 코치입니다. 이력서와 포트폴리오를 분석했습니다. 현재 건강 점수는 {score}/100입니다. 오늘 지원서를 개선하는 데 어떻게 도움을 드릴까요?",
  },
  es: {
    heroTitle: "Optimiza tu currículum",
    heroTitleHighlight: "en segundos",
    heroSubtitle: "Pega la descripción del trabajo y deja que nuestra IA adapte tu currículum para superar los filtros ATS y destacar ante los reclutadores.",
    step1: "Requisitos",
    step2: "Subir",
    step3: "Optimizar",
    jdLabel: "Descripción del puesto",
    jdSubLabel: "PEGA LOS REQUISITOS DEL PUESTO",
    jdPlaceholder: "Pega la descripción aquí...",
    clear: "LIMPIAR",
    yourResume: "Tu Currículum",
    resumeSubLabel: "ARCHIVO / TEXTO",
    uploadResume: "Subir Currículum",
    uploadResumeSub: "ARRASTRA O HAZ CLIC (.DOCX, .PDF)",
    pasteResume: "Pegar Currículum",
    pasteResumeSub: "PEGA TEXTO PLANO DIRECTAMENTE",
    uploadProject: "Subir Portafolio",
    uploadProjectSub: "ARRASTRA O HAZ CLIC (CUALQUIER MEDIO)",
    optimizeResume: "Optimizar Currículum",
    analyzeProject: "Analizar Proyecto",
    analyzing: "Analizando...",
    timeEstimate: "Tiempo estimado: ~15-20 segundos",
    matchScore: "Habilidades Clave",
    basedOn: "Basado en palabras clave y requisitos",
    backToUpload: "← Volver a modo de carga",
    pastePlaceholder: "Pega el texto de tu currículum aquí...",
    modeAI: "Optimización IA",
    modeManual: "Creador Manual",
    manualTitle: "Crear desde Cero",
    manualSubtitle: "Comienza con una plantilla profesional y completa tus datos manualmente.",
    startManual: "Crear Nuevo CV",
    resSummary: "RESUMEN PROFESIONAL",
    resEducation: "EDUCACIÓN",
    resExperience: "EXPERIENCIA PROFESIONAL",
    resProjects: "PROYECTOS",
    resAwards: "HONORES Y PREMIOS",
    resReferences: "REFERENCIAS",
    resVolunteering: "VOLUNTARIADO",
    resSkills: "HABILIDADES",
    resProfile: "PERFIL",
    tmplMinimalist: "Minimalista",
    tmplMinimalistDesc: "Limpio y moderno (Sans-serif)",
    tmplProfessional: "Profesional",
    tmplProfessionalDesc: "Clásico y estructurado (Serif)",
    tmplCreative: "Creativo",
    tmplCreativeDesc: "Dos columnas, visualmente atractivo",
    tmplAcademic: "Académico",
    tmplAcademicDesc: "Enfoque educativo, detallado",
    tmplGrid: "Cuadrícula",
    tmplGridDesc: "Diseño moderno con barra lateral",
    designSystem: "Sistema de Diseño",
    publish: "PUBLICAR",
    themeAccent: "Color de Acento",
    inventory: "Inventario",
    editContent: "Editar Contenido",
    createNewDesign: "Crear Nuevo Diseño",
    saveChanges: "Guardar Cambios",
    publishOnline: "PUBLICAR EN LÍNEA",
    addProjects: "Añadir Proyectos",
    importWebsite: "Importar Sitio Web",
    enterWebsiteUrl: "Introduce la URL de tu sitio web (ej. https://myportfolio.com):",
    clearAll: "Borrar Todo",
    resumeBuilder: "Constructor de CV",
    portfolioAi: "IA de Portafolio",
    interview: "Entrevista",
    careerPath: "Ruta de Carrera",
    interviewLab: "Laboratorio de Entrevistas",
    practiceContext: "Contexto de Práctica",
    recruiter: "Reclutador",
    duration: "Duración",
    mode: "Modo",
    startSession: "INICIAR SESIÓN",
    liveInfo: "Información en Vivo",
    muteMic: "SILENCIAR MIC",
    unmuteMic: "ACTIVAR MIC",
    expertFeedback: "Comentarios Expertos",
    history: "Historial",
    intResumeJd: "JD del Currículum",
    intCustom: "Personalizado",
    intCustomPlaceholder: "Pega requisitos específicos...",
    intOlivia: "Olivia",
    intJames: "James",
    intModeText: "Texto",
    intModeVoice: "Voz",
    intModeFace: "Video",
    intEnd: "FINALIZAR",
    intLiveVision: "Análisis de Visión en Vivo",
    intExpression: "Expresión",
    intEyeContact: "Contacto Visual",
    intGeneratingReport: "Generando Informe de Rendimiento...",
    intReportSubtitle: "Analizando patrones de habla, contenido y sentimiento.",
    intStudioTitle: "Estudio de Reclutamiento IA",
    intStudioReady: "Listo para tu simulación de alto riesgo.",
    intStudioWarmup: "Calentando el estudio...",
    intHistoryTitle: "Historial",
    intHistorySubtitle: "Registros Anteriores",
    intHistoryReset: "Reiniciar",
    intNoSessions: "No se encontraron sesiones",
    intEvaluationTitle: "Evaluación de Entrevista",
    intEvaluationSubtitle: "INFORME CONFIDENCIAL DEL CANDIDATO",
    intTotalScore: "Puntaje Total",
    intExecSummary: "Resumen Ejecutivo",
    intStrengths: "Fortalezas",
    intGrowth: "Áreas de Crecimiento",
    intMisses: "Errores Críticos",
    intTranscript: "Análisis de Transcripción",
    intDownloadPdf: "Descargar Informe PDF",
    intClose: "Cerrar",
    intTime: "Hora",
    intBy: "Por",
    intLen: "Dur",
    intListening: "Escuchando",
    intStandby: "En Espera",
    intProcessing: "Procesando...",
    intTypeResponse: "Escribe tu respuesta...",
    intSpeakNow: "Te escucho, por favor habla...",
    cpAiTitle: "IA de Estrategia",
    cpMapFuture: "Mapa de tu Futuro.",
    cpSubtitle: "Comenzando desde tu estado actual en 2026, nuestra IA evalúa cada proyecto para construir tu trayectoria única.",
    cpAutoTrajectory: "Trayectoria Auto",
    cpBasedOnResume: "Basado en CV Actual",
    cpTargetedPivot: "Pivote Dirigido",
    cpAimSpecific: "Apunta a un Rol",
    cpRecentStrategies: "Estrategias Recientes",
    cpStartOver: "Empezar de Nuevo",
    cpTimeline: "Línea de Tiempo (2026)",
    cpTargetGoal: "OBJETIVO",
    cpAnalyzing: "Analizando Datos...",
    cpBestFit: "Mejor Ajuste",
    cpMatch: "Coincidencia",
    cpViewStrategy: "Ver Estrategia",
    cpGenerating: "Generando...",
    cpConfidential: "Informe Confidencial",
    cpDownloadPdf: "Descargar PDF",
    cpSkillGap: "Análisis de Brechas",
    cpInterviewPrep: "Prep. Entrevista",
    cpPortfolioProjects: "Proyectos Portafolio",
    cpSavedPlans: "Planes Guardados",
    cpCareerRoadmaps: "Mapas de Carrera",
    cpClear: "Limpiar",
    cpNoSaved: "Sin Estrategias",
    cpTargetPlaceholder: "Rol Objetivo (ej. Gerente de Marketing Digital)",
    cpPredict: "Predecir",
    cpCurrentResume: "CV Actual",
    cpUploadNew: "Subir Nuevo PDF",
    cpCancel: "Cancelar",
    coachTriggerMessage: "{name}, veo que has descargado la estrategia de despliegue para {role}. ¿Te gustaría que te ayude a proponer ideas de proyectos específicos para cubrir la brecha de Gestión Presupuestaria que identificamos?",
    disclaimer: "AI Fast Resume es un asistente impulsado por IA; por favor, revise la precisión de todo el contenido generado.",
    authLoginRegister: "Entrar / Registrarse",
    authGoogleOneTap: "Google One-Tap",
    authOr: "O",
    authEmailAddress: "Correo Electrónico",
    authPassword: "Contraseña",
    authEmailButton: "Entrar / Registrarse por Email",
    authLoggedIn: "Sesión Iniciada",
    authProcessing: "Procesando...",
    authVerifyEmail: "¡Email de verificación enviado! Por favor, revisa tu buzón.",
    coachGreeting: "¡Hola! Soy tu Coach de Carrera IA. He analizado tu currículum y portafolio. Tu Puntuación de Salud actual es: {score}/100. ¿Cómo puedo ayudarte a mejorar tu solicitud hoy?",
  },
  de: {
    heroTitle: "Lebenslauf optimieren",
    heroTitleHighlight: "in Sekunden",
    heroSubtitle: "Fügen Sie Ihre Stellenbeschreibung ein und lassen Sie unsere KI Ihren Lebenslauf anpassen, um ATS-Filter zu bestehen.",
    step1: "Anforderungen",
    step2: "Hochladen",
    step3: "Optimieren",
    jdLabel: "Stellenbeschreibung",
    jdSubLabel: "ANFORDERUNGEN EINFÜGEN",
    jdPlaceholder: "Stellenbeschreibung hier einfügen...",
    clear: "LEEREN",
    yourResume: "Ihr Lebenslauf",
    resumeSubLabel: "QUELLE / TEXT",
    uploadResume: "CV Hochladen",
    uploadResumeSub: "DATEI ZIEHEN ODER KLICKEN (.DOCX, .PDF)",
    pasteResume: "CV Einfügen",
    pasteResumeSub: "DIREKT ALS TEXT EINFÜGEN",
    uploadProject: "Portfolio Hochladen",
    uploadProjectSub: "MEDIEN ZIEHEN ODER KLICKEN",
    optimizeResume: "CV Optimieren",
    analyzeProject: "Projekt Analysieren",
    analyzing: "Analysiere...",
    timeEstimate: "Geschätzte Zeit: ~15-20 Sekunden",
    matchScore: "Kernkompetenzen",
    basedOn: "Basierend auf Schlüsselwörtern",
    backToUpload: "← Zurück zum Upload-Modus",
    pastePlaceholder: "Lebenslauf-Text hier einfügen...",
    modeAI: "KI-Optimierung",
    modeManual: "Manueller Editor",
    manualTitle: "Von Grund auf neu erstellen",
    manualSubtitle: "Beginnen Sie mit einer professionellen Vorlage und füllen Sie Ihre Details manuell aus.",
    startManual: "Neuen CV erstellen",
    resSummary: "BERUFLICHE ZUSAMMENFASSUNG",
    resEducation: "AUSBILDUNG",
    resExperience: "BERUFSERFAHRUNG",
    resProjects: "PROJEKTE",
    resAwards: "AUSZEICHNUNGEN",
    resReferences: "REFERENZEN",
    resVolunteering: "EHRENAMT",
    resSkills: "KOMPETENZEN",
    resProfile: "PROFIL",
    tmplMinimalist: "Minimalistisch",
    tmplMinimalistDesc: "Sauber & modern (Sans-Serif)",
    tmplProfessional: "Professionell",
    tmplProfessionalDesc: "Klassisch & strukturiert (Serif)",
    tmplCreative: "Kreativ",
    tmplCreativeDesc: "Zweispaltig, visuell ansprechend",
    tmplAcademic: "Akademisch",
    tmplAcademicDesc: "Bildungsorientiert, detailreich",
    tmplGrid: "Raster",
    tmplGridDesc: "Modernes Seitenleisten-Layout",
    designSystem: "Design-System",
    publish: "VERÖFFENTLICHEN",
    themeAccent: "Akzentfarbe",
    inventory: "Inventar",
    editContent: "Inhalt Bearbeiten",
    createNewDesign: "Neues Design Erstellen",
    saveChanges: "Änderungen Speichern",
    publishOnline: "ONLINE VERÖFFENTLICHEN",
    addProjects: "Projekte Hinzufügen",
    clearAll: "Alle Daten Löschen",
    resumeBuilder: "Lebenslauf-Editor",
    portfolioAi: "Portfolio-KI",
    interview: "Interview",
    careerPath: "Karriereweg",
    interviewLab: "Interview-Labor",
    practiceContext: "Übungskontext",
    recruiter: "Personalvermittler",
    duration: "Dauer",
    mode: "Modus",
    startSession: "SITZUNG STARTEN",
    liveInfo: "Live-Info",
    muteMic: "STUMMSCHALTEN",
    unmuteMic: "MIKRO AN",
    expertFeedback: "Expertenfeedback",
    history: "Verlauf",
    intResumeJd: "LEBENSLAUF JD",
    intCustom: "BENUTZERDEFINIERT",
    intCustomPlaceholder: "Spezifische Anforderungen einfügen...",
    intOlivia: "Olivia",
    intJames: "James",
    intModeText: "Text",
    intModeVoice: "Stimme",
    intModeFace: "Video",
    intEnd: "ENDE",
    intLiveVision: "Live-Visionsanalyse",
    intExpression: "Ausdruck",
    intEyeContact: "Blickkontakt",
    intGeneratingReport: "Leistungsbericht wird erstellt...",
    intReportSubtitle: "Analyse von Sprachmustern, Inhalt und Stimmung.",
    intStudioTitle: "KI-Recruiter-Studio",
    intStudioReady: "Bereit für Ihre Simulation.",
    intStudioWarmup: "Studio wird aufgewärmt...",
    intHistoryTitle: "Verlauf",
    intHistorySubtitle: "Frühere Protokolle",
    intHistoryReset: "Zurücksetzen",
    intNoSessions: "Keine Sitzungen gefunden",
    intEvaluationTitle: "Interview-Bewertung",
    intEvaluationSubtitle: "VERTRAULICHER KANDIDATENBERICHT",
    intTotalScore: "Gesamtpunktzahl",
    intExecSummary: "Zusammenfassung",
    intStrengths: "Stärken",
    intGrowth: "Wachstumsbereiche",
    intMisses: "Kritische Fehler",
    intTranscript: "Transkript-Analyse",
    intDownloadPdf: "PDF-Bericht herunterladen",
    intClose: "Schließen",
    intTime: "Zeit",
    intBy: "Von",
    intLen: "Dauer",
    intListening: "Zuhören",
    intStandby: "Bereit",
    intProcessing: "Verarbeitung...",
    intTypeResponse: "Antwort eingeben...",
    intSpeakNow: "Ich höre zu, bitte sprechen Sie...",
    cpAiTitle: "Karriere-Strategie-KI",
    cpMapFuture: "Planen Sie Ihre Zukunft.",
    cpSubtitle: "Basierend auf Ihrem Status 2026 bewertet unsere KI jedes Projekt, um Ihren einzigartigen Karriereweg zu erstellen.",
    cpAutoTrajectory: "Auto-Trajektorie",
    cpBasedOnResume: "Basierend auf aktuellem CV",
    cpTargetedPivot: "Gezielter Wechsel",
    cpAimSpecific: "Zielrolle anstreben",
    cpRecentStrategies: "Aktuelle Strategien",
    cpStartOver: "Neu starten",
    cpTimeline: "Zeitplan (Start: 2026)",
    cpTargetGoal: "ZIEL",
    cpAnalyzing: "Analysiere Daten...",
    cpBestFit: "Beste Passung",
    cpMatch: "Übereinstimmung",
    cpViewStrategy: "Strategie anzeigen",
    cpGenerating: "Generiere...",
    cpConfidential: "Vertraulicher Bericht",
    cpDownloadPdf: "PDF herunterladen",
    cpSkillGap: "Kompetenzlücken",
    cpInterviewPrep: "Interview-Vorb.",
    cpPortfolioProjects: "Portfolio-Projekte",
    cpSavedPlans: "Gespeicherte Pläne",
    cpCareerRoadmaps: "Karriere-Roadmaps",
    cpClear: "Löschen",
    cpNoSaved: "Keine Strategien",
    cpTargetPlaceholder: "Zielrolle (z.B. Marketing Manager)",
    cpPredict: "Vorhersagen",
    cpCurrentResume: "Aktueller CV",
    cpUploadNew: "Neues PDF hochladen",
    cpCancel: "Abbrechen",
    coachTriggerMessage: "{name}, ich sehe, dass Sie die Einsatzstrategie für {role} heruntergeladen haben. Möchten Sie, dass ich Ihnen helfe, einige konkrete Projektideen zu entwickeln, um die Lücke im Budgetmanagement zu schließen?",
    disclaimer: "AI Fast Resume ist ein KI-gestützter Assistent; bitte überprüfen Sie alle generierten Inhalte auf ihre Richtigkeit.",
    authLoginRegister: "Anmelden / Registrieren",
    authGoogleOneTap: "Google One-Tap",
    authOr: "ODER",
    authEmailAddress: "E-Mail-Adresse",
    authPassword: "Passwort",
    authEmailButton: "E-Mail Anmelden / Registrieren",
    authLoggedIn: "Angemeldet",
    authProcessing: "Verarbeitung...",
    authVerifyEmail: "Bestätigungs-E-Mail gesendet! Bitte prüfen Sie Ihr Postfach.",
    coachGreeting: "Hallo! Ich bin Ihr KI-Karriere-Coach. Ich habe Ihren Lebenslauf und Ihr Portfolio analysiert. Ihr aktueller Gesundheits-Score beträgt: {score}/100. Wie kann ich Ihnen heute helfen, Ihre Bewerbung zu verbessern?",
  },
  fr: {
    heroTitle: "Optimisez votre CV",
    heroTitleHighlight: "en quelques secondes",
    heroSubtitle: "Collez votre offre d'emploi et laissez notre IA adapter votre CV pour passer les filtres ATS.",
    step1: "Exigences",
    step2: "Télécharger",
    step3: "Optimiser",
    jdLabel: "Description du poste",
    jdSubLabel: "COLLEZ LES EXIGENCES DU POSTE",
    jdPlaceholder: "Collez la description ici...",
    clear: "EFFACER",
    yourResume: "Votre CV",
    resumeSubLabel: "SOURCE / TEXTE",
    uploadResume: "Télécharger CV",
    uploadResumeSub: "GLISSER OU CLIQUER (.DOCX, .PDF)",
    pasteResume: "Coller CV",
    pasteResumeSub: "COLLER DIRECTEMENT LE TEXTE",
    uploadProject: "Télécharger Portfolio",
    uploadProjectSub: "GLISSER OU CLIQUER (MÉDIAS)",
    optimizeResume: "Optimiser le CV",
    analyzeProject: "Analyser le Projet",
    analyzing: "Analyse...",
    timeEstimate: "Temps estimé : ~15-20 secondes",
    matchScore: "Compétences clés",
    basedOn: "Basé sur les mots-clés",
    backToUpload: "← Retour au mode téléchargement",
    pastePlaceholder: "Collez le texte de votre CV ici...",
    modeAI: "Optimisation IA",
    modeManual: "Éditeur Manuel",
    manualTitle: "Créer à partir de zéro",
    manualSubtitle: "Commencez avec un modèle professionnel et remplissez vos détails manuellement.",
    startManual: "Créer un nouveau CV",
    resSummary: "RÉSUMÉ PROFESSIONNEL",
    resEducation: "FORMATION",
    resExperience: "EXPÉRIENCE PROFESSIONNELLE",
    resProjects: "PROJETS",
    resAwards: "PRIX ET DISTINCTIONS",
    resReferences: "RÉFÉRENCES",
    resVolunteering: "BÉNÉVOLAT",
    resSkills: "COMPÉTENCES",
    resProfile: "PROFIL",
    tmplMinimalist: "Minimaliste",
    tmplMinimalistDesc: "Propre et moderne (Sans serif)",
    tmplProfessional: "Professionnel",
    tmplProfessionalDesc: "Classique et structuré (Serif)",
    tmplCreative: "Créatif",
    tmplCreativeDesc: "Deux colonnes, visuellement attrayant",
    tmplAcademic: "Académique",
    tmplAcademicDesc: "Priorité à l'éducation, détaillé",
    tmplGrid: "Grille",
    tmplGridDesc: "Mise en page moderne avec barre latérale",
    designSystem: "Système de Design",
    publish: "PUBLIER",
    themeAccent: "Couleur d'accent",
    inventory: "Inventaire",
    editContent: "Modifier Contenu",
    createNewDesign: "Créer un Nouveau Design",
    saveChanges: "Enregistrer",
    publishOnline: "PUBLIER EN Ligne",
    addProjects: "Ajouter Projets",
    clearAll: "Effacer tout",
    resumeBuilder: "Générateur de CV",
    portfolioAi: "Portfolio IA",
    interview: "Entretien",
    careerPath: "Carrière",
    interviewLab: "Labo d'entretien",
    practiceContext: "Contexte de pratique",
    recruiter: "Recruteur",
    duration: "Durée",
    mode: "Mode",
    startSession: "LANCER SESSION",
    liveInfo: "Infos Live",
    muteMic: "MICRO MUET",
    unmuteMic: "ACTIVER MICRO",
    expertFeedback: "Retour Expert",
    history: "Historique",
    intResumeJd: "JD du CV",
    intCustom: "PERSONNALISÉ",
    intCustomPlaceholder: "Collez les exigences spécifiques...",
    intOlivia: "Olivia",
    intJames: "James",
    intModeText: "Texte",
    intModeVoice: "Voix",
    intModeFace: "Vidéo",
    intEnd: "FIN",
    intLiveVision: "Analyse Visuelle Live",
    intExpression: "Expression",
    intEyeContact: "Contact Visuel",
    intGeneratingReport: "Génération du rapport...",
    intReportSubtitle: "Analyse des modèles de parole, du contenu et des sentiments.",
    intStudioTitle: "Studio Recruteur IA",
    intStudioReady: "Prêt pour votre simulation.",
    intStudioWarmup: "Le studio chauffe...",
    intHistoryTitle: "Historique",
    intHistorySubtitle: "Journaux Précédents",
    intHistoryReset: "Réinitialiser",
    intNoSessions: "Aucune session trouvée",
    intEvaluationTitle: "Évaluation d'Entretien",
    intEvaluationSubtitle: "RAPPORT CANDIDAT CONFIDENTIEL",
    intTotalScore: "Score Total",
    intExecSummary: "Résumé Exécutif",
    intStrengths: "Points Forts",
    intGrowth: "Axes de Progrès",
    intMisses: "Erreurs Critiques",
    intTranscript: "Analyse de Transcription",
    intDownloadPdf: "Télécharger Rapport PDF",
    intClose: "Fermer",
    intTime: "Heure",
    intBy: "Par",
    intLen: "Durée",
    intListening: "Écoute",
    intStandby: "Prêt",
    intProcessing: "Traitement...",
    intTypeResponse: "Tapez votre réponse...",
    intSpeakNow: "Je vous écoute, parlez...",
    cpAiTitle: "IA Stratégie Carrière",
    cpMapFuture: "Tracez votre avenir.",
    cpSubtitle: "À partir de votre statut en 2026, notre IA évalue chaque projet pour construire votre trajectoire unique.",
    cpAutoTrajectory: "Trajectoire Auto",
    cpBasedOnResume: "Basé sur CV actuel",
    cpTargetedPivot: "Pivot Ciblé",
    cpAimSpecific: "Viser un rôle",
    cpRecentStrategies: "Stratégies Récentes",
    cpStartOver: "Recommencer",
    cpTimeline: "Chronologie (2026)",
    cpTargetGoal: "OBJECTIF",
    cpAnalyzing: "Analyse des données...",
    cpBestFit: "Meilleur choix",
    cpMatch: "Correspondance",
    cpViewStrategy: "Voir Stratégie",
    cpGenerating: "Génération...",
    cpConfidential: "Rapport Confidentiel",
    cpDownloadPdf: "Télécharger PDF",
    cpSkillGap: "Écart de Compétences",
    cpInterviewPrep: "Prép. Entretien",
    cpPortfolioProjects: "Projets Portfolio",
    cpSavedPlans: "Plans Sauvegardés",
    cpCareerRoadmaps: "Feuilles de Route",
    cpClear: "Effacer",
    cpNoSaved: "Aucune stratégie",
    cpTargetPlaceholder: "Rôle Cible (ex: Chef de Projet)",
    cpPredict: "Prédire",
    cpCurrentResume: "CV Actuel",
    cpUploadNew: "Nouveau PDF",
    cpCancel: "Annuler",
    coachTriggerMessage: "{name}, je vois que vous avez téléchargé la stratégie de déploiement pour {role}. Voulez-vous que je vous aide à trouver des idées de projets spécifiques pour combler les lacunes en gestion budgétaire ?",
    disclaimer: "AI Fast Resume est un assistant alimenté par l'IA ; veuillez vérifier l'exactitude de tout le contenu généré.",
    authLoginRegister: "Connexion / Inscription",
    authGoogleOneTap: "Google One-Tap",
    authOr: "OU",
    authEmailAddress: "Adresse Email",
    authPassword: "Mot de passe",
    authEmailButton: "Connexion / Inscription par Email",
    authLoggedIn: "Connecté",
    authProcessing: "Traitement...",
    authVerifyEmail: "Email de vérification envoyé ! Veuillez consulter votre boîte.",
    coachGreeting: "Bonjour ! Je suis votre Coach Carrière IA. J'ai analysé votre CV et votre portfolio. Votre Score de Santé actuel est de : {score}/100. Comment puis-je vous aider à améliorer votre candidature aujourd'hui ?",
  },
  ar: {
    heroTitle: "حسن سيرتك الذاتية",
    heroTitleHighlight: "في ثوانٍ",
    heroSubtitle: "انسخ وصف الوظيفة المستهدفة ودع ذكاءنا الاصطناعي يصمم سيرتك الذاتية لاجتياز فلاتر ATS.",
    step1: "المتطلبات",
    step2: "تحميل",
    step3: "تحسين",
    jdLabel: "وصف الوظيفة",
    jdSubLabel: "انسخ متطلبات الدور الوظيفي",
    jdPlaceholder: "انسخ وصف الوظيفة هنا...",
    clear: "مسح",
    yourResume: "سيرتك الذاتية",
    resumeSubLabel: "المصدر / النص",
    uploadResume: "رفع السيرة الذاتية",
    uploadResumeSub: "اسحب الملف أو انقر للرفع (.DOCX, .PDF)",
    pasteResume: "لصق السيرة الذاتية",
    pasteResumeSub: "لصق النص مباشرة",
    uploadProject: "رفع المعرض",
    uploadProjectSub: "اسحب الملفات أو انقر للرفع",
    optimizeResume: "تحسين السيرة الذاتية",
    analyzeProject: "تحليل المشروع",
    analyzing: "جاري التحليل...",
    timeEstimate: "الوقت المقدر: ~15-20 ثانية",
    matchScore: "المهارات الأساسية",
    basedOn: "بناءً على مطابقة الكلمات المفتاحية",
    backToUpload: "← العودة لوضع التحميل",
    pastePlaceholder: "انسخ نص سيرتك الذاتية هنا...",
    modeAI: "تحسين الذكاء الاصطناعي",
    modeManual: "بناء يدوي",
    manualTitle: "البناء من الصفر",
    manualSubtitle: "ابدأ بقالب احترافي واملأ التفاصيل يدويًا.",
    startManual: "إنشاء سيرة ذاتية جديدة",
    resSummary: "الملخص المهني",
    resEducation: "التعليم",
    resExperience: "الخبرة المهنية",
    resProjects: "المشاريع",
    resAwards: "الجوائز والتكريمات",
    resReferences: "المراجع",
    resVolunteering: "العمل التطوعي",
    resSkills: "المهارات",
    resProfile: "الملف الشخصي",
    tmplMinimalist: "بسيط",
    tmplMinimalistDesc: "نظيف وحديث (Sans-serif)",
    tmplProfessional: "احترافي",
    tmplProfessionalDesc: "كلاسيكي ومنظم (Serif)",
    tmplCreative: "إبداعي",
    tmplCreativeDesc: "عمودين، جذاب بصريًا",
    tmplAcademic: "أكاديمي",
    tmplAcademicDesc: "التركيز على التعليم، مفصل",
    tmplGrid: "شبكي",
    tmplGridDesc: "تخطيط جانبي حديث",
    designSystem: "نظام التصميم",
    publish: "نشر",
    themeAccent: "لون السمة",
    inventory: "المخزون",
    editContent: "تعديل المحتوى",
    createNewDesign: "إنشاء تصميم جديد",
    saveChanges: "حفظ التغييرات",
    publishOnline: "النشر عبر الإنترنت",
    addProjects: "إضافة مشاريع",
    clearAll: "مسح كافة البيانات",
    resumeBuilder: "منشئ السيرة الذاتية",
    portfolioAi: "معرض الأعمال الذكي",
    interview: "المقابلة",
    careerPath: "المسار المهني",
    interviewLab: "مختبر المقابلات",
    practiceContext: "سياق الممارسة",
    recruiter: "المسؤول",
    duration: "المدة",
    mode: "الوضع",
    startSession: "بدء الجلسة",
    liveInfo: "معلومات مباشرة",
    muteMic: "كتم الميكروفون",
    unmuteMic: "تشغيل الميكروفون",
    expertFeedback: "تعليقات الخبراء",
    history: "السجل",
    intResumeJd: "وصف السيرة الذاتية",
    intCustom: "مخصص",
    intCustomPlaceholder: "انسخ متطلبات محددة...",
    intOlivia: "أوليفيا",
    intJames: "جيمس",
    intModeText: "نص",
    intModeVoice: "صوت",
    intModeFace: "فيديو",
    intEnd: "إنهاء",
    intLiveVision: "تحليل بصري مباشر",
    intExpression: "التعبير",
    intEyeContact: "التواصل البصري",
    intGeneratingReport: "جاري إنشاء تقرير الأداء...",
    intReportSubtitle: "تحليل أنماط الكلام والمحتوى والمشاعر.",
    intStudioTitle: "استوديو التوظيف الذكي",
    intStudioReady: "جاهز لمحاكاتك المهمة.",
    intStudioWarmup: "جاري تحضير الاستوديو...",
    intHistoryTitle: "السجل",
    intHistorySubtitle: "السجلات السابقة",
    intHistoryReset: "إعادة تعيين",
    intNoSessions: "لم يتم العثور على جلسات",
    intEvaluationTitle: "تقييم المقابلة",
    intEvaluationSubtitle: "تقرير مرشح سري",
    intTotalScore: "النتيجة الإجمالية",
    intExecSummary: "ملخص تنفيذي",
    intStrengths: "أبرز نقاط القوة",
    intGrowth: "مجالات النمو",
    intMisses: "الأخطاء الحرجة",
    intTranscript: "تحليل النص",
    intDownloadPdf: "تنزيل تقرير PDF",
    intClose: "إغلاق",
    intTime: "الوقت",
    intBy: "بواسطة",
    intLen: "المدة",
    intListening: "جاري الاستماع",
    intStandby: "استعداد",
    intProcessing: "جاري المعالجة...",
    intTypeResponse: "اكتب الإجابة...",
    intSpeakNow: "أنا أستمع، يرجى التحدث...",
    cpAiTitle: "استراتيجية المهنة الذكية",
    cpMapFuture: "ارسم مستقبلك.",
    cpSubtitle: "بدءًا من وضعك الحالي في 2026، يقوم الذكاء الاصطناعي بتقييم كل مشروع لبناء مسارك المهني الفريد.",
    cpAutoTrajectory: "المسار التلقائي",
    cpBasedOnResume: "بناءً على السيرة الذاتية",
    cpTargetedPivot: "تحول مستهدف",
    cpAimSpecific: "استهدف دورًا محددًا",
    cpRecentStrategies: "الاستراتيجيات الأخيرة",
    cpStartOver: "البدء من جديد",
    cpTimeline: "الجدول الزمني (2026)",
    cpTargetGoal: "الهدف",
    cpAnalyzing: "تحليل البيانات المهنية",
    cpBestFit: "الأنسب",
    cpMatch: "تطابق",
    cpViewStrategy: "عرض الاستراتيجية",
    cpGenerating: "جاري الإنشاء...",
    cpConfidential: "تقرير سري",
    cpDownloadPdf: "تنزيل PDF",
    cpSkillGap: "تحليل فجوة المهارات",
    cpInterviewPrep: "تحضير المقابلة",
    cpPortfolioProjects: "مشاريع المعرض",
    cpSavedPlans: "الخطط المحفوظة",
    cpCareerRoadmaps: "خرائط الطريق المهنية",
    cpClear: "مسح",
    cpNoSaved: "لا توجد استراتيجيات محفوظة",
    cpTargetPlaceholder: "الدور المستهدف (مثل مدير التسويق الرقمي)",
    cpPredict: "تنبؤ",
    cpCurrentResume: "السيرة الذاتية الحالية",
    cpUploadNew: "رفع PDF جديد",
    cpCancel: "إلغاء",
    coachTriggerMessage: "{name}، أرى أنك قمت بتنزيل استراتيجية النشر لـ {role}. هل ترغب في أن أساعدك في طرح بعض أفكار المشاريع المحددة لسد فجوة إدارة الميزانية التي حددناها سابقًا؟",
    disclaimer: "AI Fast Resume هو مساعد مدعوم بالذكاء الاصطناعي؛ يرجى مراجعة جميع المحتويات التي تم إنشاؤها للتأكد من دقتها.",
    authLoginRegister: "تسجيل الدخول / الاشتراك",
    authGoogleOneTap: "Google ون تاتش",
    authOr: "أو",
    authEmailAddress: "البريد الإلكتروني",
    authPassword: "كلمة المرور",
    authEmailButton: "دخول / اشتراك بالبريد",
    authLoggedIn: "تم تسجيل الدخول",
    authProcessing: "جاري المعالجة...",
    authVerifyEmail: "تم إرسال بريد التحقق! يرجى فحص صندوق الوارد.",
    coachGreeting: "مرحبًا! أنا مدربك المهني بالذكاء الاصطناعي. لقد قمت بتحليل سيرتك الذاتية ومعرض أعمالك. درجة صحتك الحالية هي: {score}/100. كيف يمكنني مساعدتك في تحسين طلبك اليوم؟",
  }
};
